services:
  postgres:
    image: postgres:16
    network_mode: host # remove in production
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: twn
      POSTGRES_PASSWORD: twn
      POSTGRES_DB: twn
    volumes:
      - pgdata-prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U twn -d twn"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pg

  twn:
    image: ghcr.io/infybtw/twn
    network_mode: host # remove in production
    build:
      context: .
      dockerfile: app/Dockerfile
      network: host
    env_file: .env
    restart: unless-stopped
    networks:
      - pg
    volumes:
      - ./logs/prod:/app/logs
    depends_on:
      postgres:
        condition: service_healthy

  twn-web:
    image: ghcr.io/infybtw/twn-web
    network_mode: host # remove in production
    build:
      context: .
      dockerfile: web-admin/Dockerfile
      network: host
    restart: unless-stopped
    depends_on:
      twn:
        condition: service_healthy

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - pg

  pgbackweb:
    image: eduardolat/pgbackweb:latest
    ports:
      - "8085:8085"
    volumes:
      - ./backups:/backups
    environment:
      PBW_ENCRYPTION_KEY: "secret_key"
      PBW_POSTGRES_CONN_STRING: "postgresql://twn:twn@localhost:5432/pgbackweb?sslmode=disable"
      PBW_PATH_PREFIX: "/pgback"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - pg

volumes:
  pgdata-prod:
  caddy_data:

networks:
  pg:
    driver: bridge
